apiVersion: v1
kind: Service
metadata:
  name: billtop40-service
spec:
  selector:
    app: billtop40-web-pod
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: billtop40-psql-service
spec:
  selector:
    app: billtop40-psql-pod
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billtop40-psql
spec:
  selector:
    matchLabels:
      app: billtop40-psql-pod
  template:
    metadata:
      labels:
        app: billtop40-psql-pod
    spec:
      containers:
      - name: billtop40-psql
        image: postgres:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:        
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "billboard"
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billtop40-server
spec:
  selector:
    matchLabels:
      app: billtop40-server-pod
  template:
    metadata:
      labels:
        app: billtop40-server-pod
    spec:
      containers:
      - name: billtop40-server
        image: huferry/billboard-server:latest
        env:
          - name: DB_CONNECTION_STRING
            value: "host=10.101.13.24;port=5432;database=billboard;username=user;password=password"
        resources:
          limits:
            memory: "8Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billtop40-web
spec:
  selector:
    matchLabels:
      app: billtop40-web-pod
  template:
    metadata:
      labels:
        app: billtop40-web-pod
    spec:
      containers:
      - name: billtop40-web
        image: huferry/billboard-web:latest
        env:
          - name: REACT_APP_API
            value: "http://billtop40-server:81/api"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000