apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    name: billtop40-web-service
    app: billtop40
spec:
  type: NodePort
  selector:
    name: billtop40-web-pod
    app: billtop40    
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30005
